version: "3.9"
services:
  server:
    build:  ./server
    ports: 
    - "5000:5000"
    volumes: 
    - ./server:/app
    environment: 
      FLASK_ENV: development
    depends_on:
      - db

  web:
    build: ./client
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/user/src/app
    depends_on: 
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: master
      POSTGRES_PASSWORD: GCH2tuj1egk
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - server
      - web
      - db

volumes:
    db-data:
